export type Lang = "en" | "fr" | "ar";
export const translations: Record<Lang, Record<string, string>> = {
  en: { brand: "Lumina", tagline: "Your AI-Powered Creative Studio", navServices: "Services", navWork: "Work", navBuild: "Build", navPricing: "Pricing", navContact: "Contact", startProject: "Start Your Project", exploreWork: "Explore Our Work", heroTitle: "Turn Your Ideas Into Stunning Content With AI.", heroSub: "AI-powered video, visuals, editing and social media content — created exactly the way you want.", support: "We create, edit, enhance and optimize professional content for brands, businesses, creators and individuals.", servicesTitle: "Everything You Need To Create Better Content.", learnMore: "Learn More", requestService: "Request This Service", buildTitle: "Build Your Content", yourProject: "Your Project", estimatedPrice: "Estimated Price", submitProject: "Submit My Project", portfolioTitle: "Our Creative Work", beforeAfter: "Before / After", howTitle: "How It Works", pricingTitle: "Flexible Pricing", whyTitle: "Why Work With Us?", testimonialsTitle: "What Clients Say", ctaTitle: "Have An Idea? Let's Turn It Into Content.", ctaSub: "Tell us what you need and we'll create a solution tailored to your vision.", startMy: "Start My Project", contactUs: "Contact Us", contactTitle: "Get In Touch", startingFrom: "Starting from", customOffer: "Tell us what you need and we'll create a custom offer." },
  fr: { brand: "Lumina", tagline: "Votre studio créatif propulsé par l'IA", navServices: "Services", navWork: "Réalisations", navBuild: "Créer", navPricing: "Tarifs", navContact: "Contact", startProject: "Démarrer votre projet", exploreWork: "Découvrir nos travaux", heroTitle: "Transformez vos idées en contenus exceptionnels grâce à l'IA.", heroSub: "Vidéo, visuels, montage et contenus sociaux — créés exactement comme vous le souhaitez.", support: "Nous créons, montons et optimisons des contenus professionnels.", servicesTitle: "Tout ce qu'il faut pour un meilleur contenu.", learnMore: "En savoir plus", requestService: "Demander ce service", buildTitle: "Construisez votre contenu", yourProject: "Votre projet", estimatedPrice: "Prix estimé", submitProject: "Envoyer mon projet", portfolioTitle: "Nos créations", beforeAfter: "Avant / Après", howTitle: "Comment ça marche", pricingTitle: "Tarifs flexibles", whyTitle: "Pourquoi nous choisir ?", testimonialsTitle: "Ils en parlent", ctaTitle: "Une idée ? Transformons-la en contenu.", ctaSub: "Dites-nous ce dont vous avez besoin.", startMy: "Lancer mon projet", contactUs: "Nous contacter", contactTitle: "Contact", startingFrom: "À partir de", customOffer: "Offre sur mesure." },
  ar: { brand: "لومينا", tagline: "استوديوكم الإبداعي المدعوم بالذكاء الاصطناعي", navServices: "الخدمات", navWork: "أعمالنا", navBuild: "ابنِ محتواك", navPricing: "الأسعار", navContact: "تواصل", startProject: "ابدأ مشروعك", exploreWork: "استكشف أعمالنا", heroTitle: "حوّل أفكارك إلى محتوى مذهل بالذكاء الاصطناعي.", heroSub: "فيديو، صور، مونتاج ومحتوى اجتماعي — يُصنع تماماً كما تريد.", support: "نبتكر ونحرّر ونحسّن المحتوى الاحترافي.", servicesTitle: "كل ما تحتاجه لصناعة محتوى أفضل.", learnMore: "اعرف المزيد", requestService: "اطلب هذه الخدمة", buildTitle: "ابنِ محتواك", yourProject: "مشروعك", estimatedPrice: "السعر التقديري", submitProject: "أرسل مشروعي", portfolioTitle: "أعمالنا الإبداعية", beforeAfter: "قبل / بعد", howTitle: "كيف نعمل", pricingTitle: "أسعار مرنة", whyTitle: "لماذا نعمل معنا؟", testimonialsTitle: "آراء العملاء", ctaTitle: "لديك فكرة؟ لنحوّلها إلى محتوى.", ctaSub: "أخبرنا بما تحتاج وسنصمّم حلاً يناسب رؤيتك.", startMy: "ابدأ مشروعي", contactUs: "تواصل معنا", contactTitle: "تواصل معنا", startingFrom: "يبدأ من", customOffer: "عرض مخصص." }
};
export const services = [
  { id: "ai-video", title: "AI Video Creation", desc: "Create cinematic and engaging videos using AI.", icon: "film" },
  { id: "editing", title: "Professional Video Editing", desc: "Cut, edit, synchronize and professionally structure your videos.", icon: "scissors" },
  { id: "ai-content", title: "AI Content Creation", desc: "Create unique digital content using advanced AI tools.", icon: "spark" },
  { id: "captions", title: "Captions & Subtitles", desc: "Add accurate, synchronized and visually attractive captions.", icon: "type" },
  { id: "voice", title: "AI Voice Over", desc: "Generate professional voice-over in different languages.", icon: "mic" },
  { id: "images", title: "AI Image Creation", desc: "Create high-quality promotional and creative images.", icon: "image" },
  { id: "enhance", title: "Video & Image Enhancement", desc: "Improve resolution, sharpness, lighting and quality.", icon: "enhance" },
  { id: "social", title: "Social Media Content", desc: "Content optimized for TikTok, Reels, Shorts and Facebook.", icon: "social" },
  { id: "ads", title: "Advertising Content", desc: "Promotional videos and social media advertising creatives.", icon: "megaphone" },
  { id: "custom", title: "Custom Creative Projects", desc: "A completely customized service based on your idea.", icon: "star" }
];
